config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations"
  }

  resources :users

  resources :search

  resources :tags, only: [:index, :show, :destroy]

  resources :blogs do
  	resources :posts do
  		resources :comments
      collection do
        get 'search'
      end
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'posts#downvote'
        get 'favourite', to: 'posts#favourite'
        get 'unfavourite', to:'posts#unfavourite'
      end
  	end
  end

  root 'home#index'
  get 'blogs/index'
  get 'search/index'
  
  get 'blogs/:id/visited_view' => "blogs#visited_view", :as => :visited_view
  get 'blogs/:id/recent_view' => "blogs#recent_view", :as => :recent_view
  get 'blogs/:id/reacted_view' => "blogs#reacted_view", :as => :reacted_view
  get 'blogs/:id/followed', to: 'blogs#follow', :as => :follow
  get 'blogs/:id/unfollowed', to: 'blogs#unfollow', :as => :unfollow
  get 'blogs/:id/change_suspended', to:'blogs#change_suspended', :as => :change_suspended
  get 'blogs/:id/favourite', to: 'blogs#favourite', :as => :favourite
  get 'blogs/:id/unfavourite', to:'blogs#unfavourite', :as => :unfavourite
  get 'users/upgrade/:id', to: 'users#upgrade', :as => :upgrade
  get 'users/:id/visited_view' => "users#visited_view", :as => :visited_user
  get 'users/:id/recent_view' => "users#recent_view", :as => :recent_user
  get 'blogs/:id/editors', to: 'blogs#editors', :as => :editors
  post 'blogs/:id/add_editors', to: 'blogs#add_editors', :as => :add_editor
  get 'blogs/:id/remove_editors/:user_id', to: 'blogs#remove_editors', :as => :remove_editor
  get 'admin_panel/index'
  get 'users/:id/change_status', to:'users#change_status', :as => :change_status
  get 'users/:id/all', to: 'users#all', :as => :see_all

  match '*path' => 'application#render_404', via: :all
end

app/models/blog.rb
class Blog < ApplicationRecord

	is_impressionable
	acts_as_followable
  	acts_as_favoritable
	is_impressionable :counter_cache => true, :column_name => :impressions_count
	has_many :posts, dependent: :destroy

	mount_uploader :header, ImageUploader
	validates_integrity_of :header
	validates_processing_of :header

	mount_uploader :profile, ImageUploader
	validates_integrity_of :profile
	validates_processing_of :profile

	belongs_to :user

	validates :name, presence: true, length: { minimum: 5 }

	before_create do
		self.suspended = false
	end

	


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	before_action :check_user, except: [ :index, :show, :new, :create, :follow, :unfollow, :favourite, :unfavourite]
	impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

	def index
		@blogs = Blog.all
	end

	def search
		@blogs = Blog.search(params)
	end

	def show
		@blog = Blog.find(params[:id])
		@posts = Post.where(blog_id: @blog)
		@filter = "Most Recent"
		@shown_posts = @blog.posts.last(5)
		render 'show'
	end

	def editors
		@blog = Blog.find(params[:id])
		@editors = Array.new()
		if @blog.editors.blank?
			redirect_to blog_path(@blog)
			return
		else
			@editors_array = @blog.editors.split("/").map(&:to_i)
			@editors_array.each do |editors|
				@editors << User.find(editors)
			end
		end
	end

	def add_editors
		@blog = Blog.find(params[:id])
		@user = User.find_by_email(params[:email])
		@posts = Post.where(blog_id: @blog)
		@shown_posts = @blog.posts.last(5)

		if @user.nil? || @user.id == @blog.user.id
			redirect_to blog_path(@blog)
			return
		end
		if @blog.editors.nil?
			@blog.editors = @user.id.to_s << "/"
		else
			@editors_array = @blog.editors.split("/").map(&:to_i)
			if @editors_array.include?(@user.id)
				redirect_to user_path
			else
				@blog.editors << @user.id.to_s << "/" 
			end
		end
		@blog.save
		redirect_to blog_path(@blog)
	end

	def remove_editors
		@blog = Blog.find(params[:id])
		@editors_array = @blog.editors.split("/").map(&:to_s)
		@new_editors = ""
		if @editors_array.include?(params[:user_id])
			@editors_array.delete(params[:user_id])
		else
			redirect_to blog_path(@blog)
			return
		end
		@editors_array.each do |editors|
			@new_editors << editors.to_s << "/"
		end
		@blog.editors = @new_editors
		@blog.save
		redirect_to blog_path(@blog)
	end

	def follow
		@blog = Blog.find(params[:id])
		current_user.follow(@blog)
		show
	end

	def unfollow
		@blog = Blog.find(params[:id])
		current_user.stop_following(@blog)
		show
	end

	def favourite
		@blog = Blog.find(params[:id])
		current_user.favorite(@blog)
		show
	end

	def unfavourite
		@blog = Blog.find(params[:id])
		current_user.remove_favorite(@blog)
		show
	end

	def visited_view
		@filter = "Most Visited"
		@posts = Post.where(blog_id: @blog)
		@shown_posts = @blog.posts.order(:impressions_count).reverse.last(5)
		render 'show'
	end

	def recent_view
		@filter = "Most Recent"
		@posts = Post.where(blog_id: @blog)
		@shown_posts = @blog.posts.last(5)
		render 'show'
	end

	def reacted_view
		@filter = "Most Reacted"
		@posts = Post.where(blog_id: @blog)
		@shown_posts = @blog.posts.order(:cached_votes_total).reverse.last(5)
		render 'show'
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:id])

		if @blog.update(blog_params)
			redirect_to @blog
		else
			render 'edit'
		end
	end

	def new
		if user_signed_in?
			if current_user.role.to_s == "bloggoer"
				@blog = current_user.blogs.build
			else
				redirect_to '/'
			end
		else
			redirect_to '/'
		end
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy

		if current_user.admin?
			redirect_to admin_panel_index_path
		else
			redirect_to blogs_path
		end
	end

	def change_suspended
		@blog = Blog.find(params[:id])

		if current_user.admin?
			if @blog.suspended == true
				@blog.suspended = false
			else
				@blog.suspended = true
			end
		end
		@blog.save
		redirect_to admin_panel_index_path
	end

	def create
		@blog = current_user.blogs.build(blog_params)

		if @blog.save
			redirect_to @blog
		else
			render 'new'
		end
	end

	private
	def blog_params
		params.require(:blog).permit(:name, :description, :editors, :header, :profile)
	end

	private
	def check_user
		@blog = Blog.find(params[:id])
		redirect_to blog_path(@blog) unless @blog.user == current_user
	end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="card" style="width: 100%; height: 50%;">
	<div class="card-body tg-wrap" style="width: 100%;">
		<table width="100%" height="50%">
			<tr>
				<td colspan="2" align="left" valign="top">
					<% if blog.profile? %>
						<%= image_tag(blog.profile.url, alt: blog.profile.identifier, class: 'image-link-aux') %>
					<% else %>
						<%= image_tag(asset_path('blog_profile_example.jpg'), alt: blog.user.name, class: 'image-link-aux')  %>
					<% end %>
				</td>
				<td colspan="2" align="left" valign="center" class="post-title-aux">
					<h5 class="post-title">
            <%= link_to blog.name, blog_path(blog), class: "blog-link" %> <small class="text-muted"> by </small>
						<% if blog.user.username %>
							<%= link_to blog.user.username, user_path(blog.user), class: "blog-link" %>
						<% else %>
							<%= link_to blog.user.name, user_path(blog.user), class: "blog-link" %>
						<% end %>
					</h5>
          <h6>
            <%= blog.description %>
          </h6>
				</td>

			</tr>
      <tr>
        <td colspan="1" align="left">
            <i class="fas fa-newspaper" style="margin-top: 5px; margin-left:1px;"></i>&nbsp;<%= blog.posts.count %>
        </td>
        <td colspan="1" align="left">
            <i class="fas fa-users" style="margin-top: 5px; margin-left:4px;"></i>&nbsp;<%= blog.followers_count %>
        </td>
      </tr>
		</table>
	</div>
</div>

app/views/blogs/_editors.html.erb
<h2>Insert credentials of the new editor:</h2>
  <form action="<%= @blog.id %>/add_editors" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <br>
    <br>
    <table class="table">
    <tr>
      <h6> email : </h6>
      <input type="text" name="email">   
    </tr>
    <br>
    <br>
    <tr>
      <input type="submit" value="Add" />
    </tr>
  </table>
</form>
</br>

app/views/blogs/_form.html.erb
<div class="jumbotron container-fluid">

<%= form_with model: @blog, local: true do |form| %>
 
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <table class="table">
    <tr>
      <th><%= form.label :name %></th>
      <th><%= form.text_field :name, id: 'name' %></th>
    </tr>
    <tr>
      <th><%= form.label :description %></th>
      <th><%= form.text_field :description, id: 'description' %></th>
    </tr>
    <tr>
      <th><%= form.label :profile %></th>
      <th><%= form.file_field :profile, id: 'profile'  %></th>
    </tr>
    <tr>
      <th><%= form.label :header %></th>
      <th><%= form.file_field :header, id: 'header' %></th>
    </tr>
  </table> 

  <div class="actions float-right">
    <%= form.submit "✔ Create Bloggo", class: "btn btn-primary", id: 'createBloggo'%>
  </div>
 
<% end %>

</div>

app/views/blogs/edit.html.erb
<div class="jumbotron">

	<h1>Edit Blog</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', blog_path(@blog), class: "btn btn-dark" %>

</div>

app/views/blogs/editors.html.erb
<div class="container">
	<div class="card" style="width: 100%;">
	<div class="card-body tg-wrap" style="width: 100%;">
	<table width="100%">
	<% @editors.each do |editor| %>
		<tr>
			<td colspan="2" align="left"  valign="top">
				<% if editor.avatar_image? %>
					<%= image_tag(editor.avatar_image.url, alt: editor.avatar_image.identifier, class: 'image-link-aux') %>
				<% else %>
					<%= image_tag(asset_path('user-placeholder.jpeg'), alt: editor.name, class: 'image-link-aux')  %>
				<% end %>
			</td>
			<td colspan="2" align="left" valign="center" class="post-title-aux">
				<% if editor.username %>
					<%= link_to editor.username, user_path(editor), class: "post-link" %>
				<% else %>
					<%= link_to editor.name, user_path(editor), class: "post-link" %> 
				<% end %>
			</td>
		</tr>
		<tr>
			<td colspan="5" align="right"  valign="top">
				<%= link_to 'Remove', remove_editor_path(@blog,editor.id), class: "btn btn-warning"%> 
			</td>
		</tr>
	<% end %>
	</table>
</div>
</div>
</div>

<style>
 .header_background{
 	background-image: url(<%= @blog.header.url.to_s %>);
 }

 .transbox {
    margin: 30px;
    background-color: #ffffff;
    border: 1px solid black;
    opacity: 0.9;
}
</style>

app/views/blogs/index.html.erb
<div class="jumbotron">

  <h1>Hello, Bloggoer!</h1>

    <% if @blogs != nil && @blogs.count != 0%>
      <table class="table">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col" colspan="3"></th>
          <th></th>
        </tr>
      <% @blogs.each do |blog| %>
        <tr>
          <td><%= blog.name %></td>
          <td><%= blog.description %></td>
          <td>di <%= link_to blog.user.email, user_path(blog.user) %></td>
          <td><%= link_to 'Show', blog_path(blog) %></td>
          <% if current_user == blog.user %>
            <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
            <td><%= link_to 'Destroy', blog_path(blog),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <h3> No blogs found! </h3>
    <% end %>
  </table>
  <% if user_signed_in? %>
    <%= link_to 'New Bloggo', new_blog_path, class: "btn btn-info" %>
  <% else %>
    <h5> Login to create a new Bloggo! </h5>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class="container">

	<div class="jumbotron">

		<h1>New Blog</h1>

		<%= render 'form' %>

		<%= link_to 'Back', blogs_path, class: "btn btn-info" %>

	</div>
	
</div>

app/views/blogs/show.html.erb
	<div class="jumbotron header_background" style="margin-top: 20px;">
		<div class="jumbotron transbox" style="margin-top: 20px;">

		<%= image_tag (@blog.profile.url.to_s) , class: "ext-center rounded mx-auto d-block", size: "300x300", alt: "Profile Pic"%>
		<h1 class="text-center"><%= @blog.name %></h1>

		<div class="row" style="margin-top: 80px; margin-left: 300px; margin-right: 300px;">
    	<div class="col-sm text-center">
      	<h3> Followers</h3>
      	<h6> <%= @blog.followers_count%> </h6>
    	</div>
    	<div class="col-sm text-center">
      	<h3> Posts</h3>
      	<h6> <%= @posts.count %></h6>
    	</div>
    	<div class="col-sm text-center">
      	<h3> Visits</h3>
      	<h6> <%= "#{@blog.impressionist_count}" %> </h6>

    	</div>
  	</div>

  	<% if user_signed_in? %>
  			<% if current_user.id == @blog.user_id %>
					<%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;"%> 
					<%= link_to 'Create Postoes', new_blog_post_path(@blog), class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;" %> 
					<%= link_to 'Add new editor', "#editorModal", "data-toggle" => "modal", class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;"%>
					<%= link_to 'Editors Control Pannel', editors_path(@blog), class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;"%> 
				<% else %>
	  			<% if current_user.id == @blog.editors %>
						<%= link_to 'Create Postoes', new_blog_post_path(@blog), class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;" %> 
					<% else %>
				  	<% if current_user.following?(@blog) %>
							<%= link_to 'Unfollow', unfollow_path(@blog), class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;"%> 
						<% else %>
							<%= link_to 'Follow', follow_path(@blog), class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;"%> 
						<% end %>
						<% if current_user.favorited?(@blog) %>
							<%= link_to 'Delete from Favourite Blogs', unfavourite_path(@blog), class: "btn btn-warning float-right", style: "margin-top: 50px; margin-bottom: -50px;"%>
						<% else %> 
							<%= link_to 'Add to Favourite Blogs', favourite_path(@blog), class: "btn btn-warning float-right", style: "margin-top: 50px; margin-bottom: -50px;"%>	
						<% end %>			
					<% end %>
				<% end %>
		<% else %>
				<%= link_to 'Sign in to follow', "#loginModal", "data-toggle" => "modal" , class: "btn btn-warning", style: "margin-top: 50px; margin-bottom: -50px;"%> 
		<% end %>
	</div>
</div>
<div class="container">

	<h6><%= @blog.description %></h6>
  <div class="dropdown float-right" style="margin-top: 120px;">
	  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"> <%= @filter %>
		  <span class="caret"></span></button>
		  <ul class="dropdown-menu" id="dropdown_view">
		    <li id="Most_Recent"><%= link_to "Most Recent", recent_view_path %></li>
		    <li id="Most_Visited"><%= link_to "Most Visited", visited_view_path %></li>
		    <li id="Most_Reacted"><%= link_to "Most Reacted", reacted_view_path %></li>
			  </ul>
	</div> 
	<div class="row">
		<div class="col-sm">
			<div class="jumbotron">
      	<h3 class="text-center"> <%= @filter %> </h3>
      		<%= render @shown_posts %>
    	</div>
    </div>

  </div>
</div>


<div class="modal" id="editorModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Editors</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "blogs/editors" %>
      </div>
    </div>
  </div>
</div>

<style>
 .header_background{
 	background-image: url(<%= @blog.header.url.to_s %>);
 }

 .transbox {
    margin: 30px;
    background-color: #ffffff;
    border: 1px solid black;
    opacity: 0.9;
}
</style>