config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations"
  }

  resources :users

  resources :search

  resources :tags, only: [:index, :show, :destroy]

  resources :blogs do
  	resources :posts do
  		resources :comments
      collection do
        get 'search'
      end
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'posts#downvote'
        get 'favourite', to: 'posts#favourite'
        get 'unfavourite', to:'posts#unfavourite'
      end
  	end
  end

  root 'home#index'
  get 'blogs/index'
  get 'search/index'
  
  get 'blogs/:id/visited_view' => "blogs#visited_view", :as => :visited_view
  get 'blogs/:id/recent_view' => "blogs#recent_view", :as => :recent_view
  get 'blogs/:id/reacted_view' => "blogs#reacted_view", :as => :reacted_view
  get 'blogs/:id/followed', to: 'blogs#follow', :as => :follow
  get 'blogs/:id/unfollowed', to: 'blogs#unfollow', :as => :unfollow
  get 'blogs/:id/change_suspended', to:'blogs#change_suspended', :as => :change_suspended
  get 'blogs/:id/favourite', to: 'blogs#favourite', :as => :favourite
  get 'blogs/:id/unfavourite', to:'blogs#unfavourite', :as => :unfavourite
  get 'users/upgrade/:id', to: 'users#upgrade', :as => :upgrade
  get 'users/:id/visited_view' => "users#visited_view", :as => :visited_user
  get 'users/:id/recent_view' => "users#recent_view", :as => :recent_user
  get 'blogs/:id/editors', to: 'blogs#editors', :as => :editors
  post 'blogs/:id/add_editors', to: 'blogs#add_editors', :as => :add_editor
  get 'blogs/:id/remove_editors/:user_id', to: 'blogs#remove_editors', :as => :remove_editor
  get 'admin_panel/index'
  get 'users/:id/change_status', to:'users#change_status', :as => :change_status
  get 'users/:id/all', to: 'users#all', :as => :see_all

  match '*path' => 'application#render_404', via: :all
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  before_action :authenticate_user!, :check_user

  def index
    @blogs = Blog.all
    @posts = Post.all
    @users = User.all.order(:id)
    @tags = ActsAsTaggableOn::Tag.all
  end

  private

  def check_user
    if current_user.admin?
		    
    else
      redirect_to root_path
    end
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/views/admin_panel/index.html.erb
<div class="container-fluid" style="margin-top:10px; margin-bottom:10px;">
  <div class="card" style="margin-bottom:10px;">
    <div class="card-header pastel_colour_blue" style="text-align:center;">
      <h2>Users Table  &nbsp;|&nbsp;  Total: <%= @users.count %> </h2>
    </div>

      <% if @users != nil && @users.count != 0%>
        <table class="table">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Username</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Status</th>
            <th scope="col" colspan="3"></th>
            <th></th>
          </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.username %></td>
            <td><%= user.name %>&nbsp;<%= user.surname %></td>
            <td><%= user.email %></td>
            <td><% if user.banned == true %>
                  BANNED
                <% else %>
                  ACTIVE
                <% end %>
            </td>
            <td><%= link_to 'Show', user_path(user), class: "btn btn-sm btn-primary", id:"show" %></td>
            <td><%= link_to 'Destroy', user_path(user),
                    method: :delete,
                    data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger", id:"destroy"  %></td>
            <td><%= link_to '<button type="button" class="btn btn-sm btn-warning">Change Status</button>'.html_safe, change_status_path(user) %>
            </td>
          </tr>
        <% end %>
      <% else %>
      <div class="card-body">
        <h3> No tags found! </h3>
      </div>
      <% end %>
  </table>
  </div>
      <div class="card" style="margin-bottom:10px;">
        <div class="card-header pastel_colour_blue" style="text-align:center;">
          <h2>Blogs Table  &nbsp;|&nbsp;  Total: <%= @blogs.count %> </h2>
        </div>
        <% if @blogs != nil && @blogs.count != 0%>
          <table class="table">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Author</th>
              <th scope="col">Status</th>
              <th scope="col" colspan="3"></th>
              <th></th>
            </tr>
          <% @blogs.each do |blog| %>
            <tr>
              <td><%= blog.name %></td>
              <td><%= blog.description %></td>
              <td>di <%= link_to blog.user.email, user_path(blog.user) %></td>
              <td><% if blog.suspended == true %>
                    SUSPENDED
                  <% else %>
                    ACTIVE
                  <% end %>
              </td>
              <td><%= link_to 'Show', blog_path(blog), class: "btn btn-sm btn-primary" %></td>
              <td><%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to 'Destroy', blog_path(blog),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger"  %></td>
              <td><%= link_to '<button type="button" class="btn btn-sm btn-warning">Change Status</button>'.html_safe, change_suspended_path(blog) %>
            </tr>
          <% end %>
        <% else %>
        <div class="card-body">
          <h3> No blogs found! </h3>
        </div>
        <% end %>

        </table>

      </div>
      <div class="card" style="margin-bottom:10px;">
        <div class="card-header pastel_colour_blue" style="text-align:center;">
          <h2>Posts Table  &nbsp;|&nbsp;  Total: <%= @posts.count %> </h2>
        </div>

          <% if @posts != nil && @posts.count != 0%>
            <table class="table">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Content</th>
                <th scope="col">Author</th>
                <th scope="col" colspan="3"></th>
                <th></th>
              </tr>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.content.html_safe %></td>
                <td>di <%= link_to post.user.email, user_path(post.user) %></td>
                <td><%= link_to 'Show', blog_post_path(post.blog, post), class: "btn btn-sm btn-primary"  %></td>
                <td><%= link_to 'Edit', edit_blog_post_path(post.blog, post), class: "btn btn-sm btn-success"  %></td>
                <td><%= link_to 'Destroy', blog_post_path(post.blog, post),
                        method: :delete,
                        data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger"  %></td>
              </tr>
            <% end %>
          <% else %>
          <div class="card-body">
            <h3> No posts found! </h3>
          </div>
          <% end %>
      </table>
      </div>
      <div class="card" style="margin-bottom:10px;">
        <div class="card-header pastel_colour_blue" style="text-align:center;">
          <h2>Tags Table  &nbsp;|&nbsp;  Total: <%= @tags.count %> </h2>
        </div>

          <% if @tags != nil && @tags.count != 0%>
            <table class="table">
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Popularity</th>
                <th scope="col" colspan="3"></th>
                <th></th>
              </tr>
            <% @tags.each do |tag| %>
              <tr>
                <td><%= tag.name %></td>
                <td><%= tag.taggings_count %></td>
                <td><%= link_to 'Show', tag_path(tag), class: "btn btn-sm btn-primary" %></td>
                <td><%= link_to 'Destroy', tag_path(tag),
                        method: :delete,
                        data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger"  %></td>
              </tr>
              <%end%>
          <% else %>
          <div class="card-body">
            <h3> No tags found! </h3>
          </div>
          <% end %>
      </table>
      </div>
</div>