config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations"
  }

  resources :users

  resources :search

  resources :tags, only: [:index, :show, :destroy]

  resources :blogs do
  	resources :posts do
  		resources :comments
      collection do
        get 'search'
      end
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'posts#downvote'
        get 'favourite', to: 'posts#favourite'
        get 'unfavourite', to:'posts#unfavourite'
      end
  	end
  end

  root 'home#index'
  get 'blogs/index'
  get 'search/index'
  
  get 'blogs/:id/visited_view' => "blogs#visited_view", :as => :visited_view
  get 'blogs/:id/recent_view' => "blogs#recent_view", :as => :recent_view
  get 'blogs/:id/reacted_view' => "blogs#reacted_view", :as => :reacted_view
  get 'blogs/:id/followed', to: 'blogs#follow', :as => :follow
  get 'blogs/:id/unfollowed', to: 'blogs#unfollow', :as => :unfollow
  get 'blogs/:id/change_suspended', to:'blogs#change_suspended', :as => :change_suspended
  get 'blogs/:id/favourite', to: 'blogs#favourite', :as => :favourite
  get 'blogs/:id/unfavourite', to:'blogs#unfavourite', :as => :unfavourite
  get 'users/upgrade/:id', to: 'users#upgrade', :as => :upgrade
  get 'users/:id/visited_view' => "users#visited_view", :as => :visited_user
  get 'users/:id/recent_view' => "users#recent_view", :as => :recent_user
  get 'blogs/:id/editors', to: 'blogs#editors', :as => :editors
  post 'blogs/:id/add_editors', to: 'blogs#add_editors', :as => :add_editor
  get 'blogs/:id/remove_editors/:user_id', to: 'blogs#remove_editors', :as => :remove_editor
  get 'admin_panel/index'
  get 'users/:id/change_status', to:'users#change_status', :as => :change_status
  get 'users/:id/all', to: 'users#all', :as => :see_all

  match '*path' => 'application#render_404', via: :all
end

app/models/user.rb
class User < ApplicationRecord
	#extend FriendlyId
	#friendly_id :username, :use => :slugged

	acts_as_voter
  	acts_as_follower
	acts_as_favoritor

	mount_uploader :avatar_image, ImageUploader

	has_many :blogs, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy

	validates_presence_of :name, :surname, :username

	#validates_presence_of   :avatar_image
	validates_integrity_of  :avatar_image
	validates_processing_of :avatar_image

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :omniauthable, :omniauth_providers => [:google_oauth2,:facebook]

	 #def self.from_omniauth(access_token)
	  # data = access_token.info
	   #user = User.where(:email => data["email"]).first

	   #unless user
	     #password = Devise.friendly_token[0,20]
	     #user = User.create(:name => data["first_name"],:surname => data["last_name"], email: data["email"],
	      # password: password, password_confirmation: password, avatar_image: data["image"]
	     #)
			# user.save!
	   #end
	  # user
	 #end

	enum role: [:user, :bloggoer, :editor, :admin]
	after_initialize :set_default_role,:set_default_banned_status, :if => :new_record?

	#def should_generate_new_friendly_id?
	#	username_changed?
	#end

	#def normalize_friendly_id(text)
		#text.to_slug.transliterate.to_s
	#end

	def set_default_role
    	self.role ||= :user
  	end

		def set_default_banned_status
     	self.banned ||= false
   	end

		def active_for_authentication?
			super && !self.banned
		end

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.first_name   # assuming the user model has a name
			user.surname = auth.info.last_name
			user.avatar_image = auth.info.image
			user.username = auth.info.first_name + " " + auth.info.last_name
			user.banned ||= false
			user.role ||= :user
			user.save!
	    # If you are using confirmable and the provider(s) you use validate emails,
	    # uncomment the line below to skip the confirmation emails.
	    # user.skip_confirmation!
	  end
	end

	def self.new_with_session(params, session)
    	super.tap do |user|
			if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def google_oauth2
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      #sign_in_and_redirect @user, :event => :authentication
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      #set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

 def failure
   redirect_to root_path
 end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  skip_before_action :verify_authenticity_token 
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
#  def create
#      @user = User.create(params.require(:user).permit(:email,:name,:surname,:password,:password_confirmation))
#  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(resource)
    root_path
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:signup, keys: [:name, :surname, :email, :password, :password_confirmation])
  #end

#  before_action :configure_permitted_parameters, if: :devise_controller?

#  def configure_permitted_parameters
#    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :surname, :email])
#    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :email, :password, :password_confirmation])
#    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :email, :password, :password_confirmation, :current_password])
#  end


  # If you have extra params to permit, append them to the sanitizer.
#   def configure_account_update_params
#     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :email, :password, :password_confirmation])
#  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  #protected

  #def after_sign_in_path_for(resource)
   #super && redirect_to root_path
  #end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]

  def index
	  @user = current_user
    @blog_count = Blog.where(user_id: @user)
		@blog = Blog.where(user_id: @user).last(5).reverse!
    @favourite_blogs = current_user.favorited_by_type 'Blog'
    @favourite_posts = current_user.favorited_by_type 'Post'
	end

  def all
    @user = current_user
    @blog = Blog.where(user_id: @user)  
  end

 	def show
		#@user = User.friendly.find(params[:id])
    @user = User.find(params[:id])
		@blog = Blog.where(user_id: @user)
    @filter = "Newest"
 	end

 	def upgrade
 		@user = current_user
 		@user.bloggoer!
    redirect_to users_url
 	end

  def change_status
    if current_user.admin?
      @user = User.find(params[:id])
      if @user.banned?
        @user.banned = false
      else
        @user.banned = true
      end
      @user.save
      redirect_to admin_panel_index_path
    else
      redirect_to root_path
    end
  end

  def destroy
    if current_user.admin?
      @user = User.find(params[:id])
      @user.destroy
		  redirect_to admin_panel_index_path
    else
      redirect_to root_path
    end
  end

  def visited_view
    @user = User.find(params[:id])
    @filter = "Most Visited"
    @blogs= Blog.where(user_id: @user)
    @blog = @blogs.order(:impressions_count).reverse.last(@blogs.count)
    render 'show'
  end

  def recent_view
    @user = User.find(params[:id])
    @filter = "Most Recent"
    @blogs = Blog.where(user_id: @user)
    @blog = @blogs.last(@blogs.count)
    render 'show'
  end

  def create
    @user = User.create(user_params)
  end

 	private
 		def user_params
		    params.require(:user).permit(:email,:name,:surname, :header, :profile)
	  end
end

app/views/users/_blog.html.erb
<% @blog.each do |blog| %>
<tr>
  <td><%= link_to blog.name, blog_path(blog) %></td>
  <td><%= blog.description %></td>
  <td><%= link_to blog.user.name, user_path(blog.user) %></td>
  <td><%= link_to blog.impressionist_count%></td>
</tr>

app/views/users/all.html.erb
<div class="container-fluid" style="margin-top:10px; margin-bottom:10px;">
  <div class="row">    
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header pastel_colour_yellow" style="text-align:center;">
          <h2>My Bloggoes</h2>
        </div>
        <div class="card-body">
        <% if @blog != nil && @blog.count != 0%>
          <table class="table">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Author</th>
              <th scope="col">Visits</th>
            </tr>
            <% @blog.each do |blog| %>
            <tr>
              <td><%= link_to blog.name, blog_path(blog) %></td>
              <td><%= blog.description %></td>
              <td><%= link_to blog.user.name, user_path(blog.user) %></td>
              <td><%= link_to blog.impressionist_count%></td>
            </tr>
            <% end %>
          </table>
          <% else %>
            <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- <link rel="stylesheet" href="styles.scss"> -->
<div class="container-fluid" style="margin-top:10px; margin-bottom:10px;">
  <div class="row">
    <div class="col-sm-6">
    	<div class="jumbotron" style="margin-top: 20px;">

    		<img class="mx-auto d-block" style="border-radius:60%; width:200px; height:200px; object-fit:cover; margin-top: 50px;" alt="User Profile Pic Example"
    		 src="<% if current_user.avatar_image? %>
    						<%= current_user.avatar_image %>
    					<% else %>
    						<%= asset_path('user-placeholder.jpeg') %>
    					<% end %>" />
    		<!-- <img src="<%= asset_path('blog_profile_example.jpg') %>" class="text-center rounded mx-auto d-block" style="margin-top: 50px;" alt="Bloggo Profile Pic Example"> -->
    		<h1 class="text-center"><%= @user.name %> <%= @user.surname %></h1>

    		<div class="row text-center">
        	<div class="col-sm-12 text-center">
          	<h3> Blogs</h3>
          	<h6> <%= @blog_count.count %></h6>
        	</div>
      	</div>
    		<% if @user.id == current_user.id %>
    			<%= link_to '<button type="button" class="btn btn-primary" id="editprofile">Edit Profile</button>'.html_safe, "#editModal", "data-toggle" => "modal", id: "editprofile" %>
    			<% if @user.bloggoer? || @user.admin? %>
    				<%= link_to '<button type="button" class="btn btn-primary">Create Bloggoes</button>'.html_safe, new_blog_path %>
    			<% else %>
    				<%= link_to '<button type="button" class="btn btn-primary">Become a Bloggoer!</button>'.html_safe, upgrade_path(current_user)%>
    			<% end %>
    		<% end %>
    	</div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header pastel_colour_yellow" style="text-align:center;">
          <h2>My Bloggoes</h2>
        </div>
        <div class="card-body">
        <% if @blog != nil && @blog.count != 0%>
          <table class="table">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Author</th>
              <th scope="col">Visits</th>
            </tr>
            <% @blog.each do |blog| %>
            <tr>
              <td><%= link_to blog.name, blog_path(blog) %></td>
              <td><%= blog.description %></td>
              <td><%= link_to blog.user.name, user_path(blog.user) %></td>
              <td><%= link_to blog.impressionist_count%></td>
            </tr>
            <% end %>
          </table>
          <% if @blog_count.count > 5 %>
            <%= link_to '<button type="button" class="btn btn-primary">See all</button>'.html_safe, see_all_path(current_user) %>
          <% end %>
          <% else %>
            <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

	<div class="modal" id="editModal" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Edit Profile</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<%= render "devise/passwords/edit" %>
					<hr />
					<%= render "devise/registrations/edit" %>
				</div>
			</div>
		</div>
	</div>

  <div class="row container-fluid">
    <div class="col-6">
      <div class="card-header pastel_colour_red " style="text-align:center;">
          <h2>Favourite Bloggoes</h2>
        </div>
        <div class="card-body">
        <% if @favourite_blogs != nil && @favourite_blogs.count != 0%>
          <table class="table">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Author</th>
              <th scope="col">Visits</th>
            </tr>
            <% @favourite_blogs.each do |blog| %>
            <tr>
              <td><%= link_to blog.name, blog_path(blog) %></td>
              <td><%= blog.description %></td>
              <td><%= link_to blog.user.name, user_path(blog.user) %></td>
              <td><%= link_to blog.impressionist_count%></td>
            </tr>
            <% end %>
          </table>
          <% else %>
            <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    <div class="col-6">
      <div class="card">
        <div class="card-header pastel_colour_red " style="text-align:center;">
          <h2>Favourite Postoes</h2>
        </div>
        <div class="card-body">
        <% if @favourite_posts != nil && @favourite_posts.count != 0%>
          <%= render @favourite_posts %>
        <% else %>
          <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- <link rel="stylesheet" href="styles.scss"> -->
<div class="container-fluid" style="margin-top:10px; margin-bottom:10px;">
  <div class="row">
    <div class="col-sm-6">
    	<div class="jumbotron" style="margin-top: 20px;">

    		<img class="mx-auto d-block" style="border-radius:60%; width:200px; height:200px; object-fit:cover; margin-top: 50px;" alt="User Profile Pic Example"
    		 src="<% if @user.avatar_image? %>
    						<%= @user.avatar_image %>
    					<% else %>
    						<%= asset_path('user-placeholder.jpeg') %>
    					<% end %>" />
    		<!-- <img src="<%= asset_path('blog_profile_example.jpg') %>" class="text-center rounded mx-auto d-block" style="margin-top: 50px;" alt="Bloggo Profile Pic Example"> -->
    		<h1 class="text-center" style="margin-top: 15px"> <%= @user.username %></h1>

    		<div class="row text-center">
        	<div class="col-sm-12 text-center">
          	<h3> Blogs</h3>
          	<h6> <%= @blog.count %></h6>
        	</div>
        </div>
      	</div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header pastel_colour_yellow" style="text-align:center;">
          <h2><%= @user.name %>'s Bloggoes</h2>
        </div>
        <div class="card-body">
        <% if @blog != nil && @blog.count != 0%>
          <table class="table">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Visits</th>
            </tr>
            <% @blog.each do |blog| %>
            <tr>
              <td><%= link_to blog.name, blog_path(blog) %></td>
              <td><%= blog.description %></td>
              <td><%= link_to blog.impressionist_count%></td>
            </tr>
            <% end %>
          </table>
      	  <div class="dropdown">
					  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><%= @filter %>
					  <span class="caret"></span></button>
					  <ul class="dropdown-menu">
					    <li> <%= link_to 'Newest'.html_safe, recent_user_path(@user) %></li>	
					  	<li> <%= link_to 'Most Visited'.html_safe, visited_user_path(@user) %></li>
	 				  </ul>
				  </div>
          <% if @blog.count > 5 %>
            <%= link_to '<button type="button" class="btn btn-primary">See all</button>'.html_safe, see_all_path(@user) %>
          <% end %>
          <% else %>
            <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/upgrade.html.erb
<!-- <link rel="stylesheet" href="styles.scss"> -->
<div class="container-fluid" style="margin-top:10px; margin-bottom:10px;">
  <div class="row">
    <div class="col-sm-6">
    	<div class="jumbotron" style="margin-top: 20px;">

    		<img class="mx-auto d-block" style="border-radius:60%; width:200px; height:200px; object-fit:cover; margin-top: 50px;" alt="User Profile Pic Example"
    		 src="<% if current_user.avatar_image? %>
    						<%= current_user.avatar_image %>
    					<% else %>
    						<%= asset_path('user-placeholder.jpeg') %>
    					<% end %>" />
    		<!-- <img src="<%= asset_path('blog_profile_example.jpg') %>" class="text-center rounded mx-auto d-block" style="margin-top: 50px;" alt="Bloggo Profile Pic Example"> -->
    		<h1 class="text-center"><%= @user.name %> <%= @user.surname %></h1>

    		<div class="row text-center">
        	<div class="col-sm-12 text-center">
          	<h3> Blogs</h3>
          	<h6> <%= @blog.count %></h6>
        	</div>
      	</div>
    		<% if @user.id == current_user.id %>
    			<%= link_to '<button type="button" class="btn btn-primary" id="editprofile">Edit Profile</button>'.html_safe, "#editModal", "data-toggle" => "modal", id: "editprofile" %>
    			<% if @user.bloggoer? || @user.admin? %>
    				<%= link_to '<button type="button" class="btn btn-primary">Create Bloggoes</button>'.html_safe, new_blog_path %>
    			<% else %>
    				<%= link_to '<button type="button" class="btn btn-primary">Become a Bloggoer!</button>'.html_safe, upgrade_path %>
    			<% end %>
    		<% end %>
    	</div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header pastel_colour_yellow" style="text-align:center;">
          <h2>My Bloggoes</h2>
        </div>
        <div class="card-body">
        <% if @blog != nil && @blog.count != 0%>
          <table class="table">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Author</th>
              <th scope="col">Visits</th>
            </tr>
            <% @blog.each do |blog| %>
            <tr>
              <td><%= link_to blog.name, blog_path(blog) %></td>
              <td><%= blog.description %></td>
              <td><%= link_to blog.user.name, user_path(blog.user) %></td>
              <td><%= link_to blog.impressionist_count%></td>
            </tr>
            <% end %>
          </table>
          <% else %>
            <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

	<div class="modal" id="editModal" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Edit Profile</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<%= render "devise/passwords/edit" %>
					<hr />
					<%= render "devise/registrations/edit" %>
				</div>
			</div>
		</div>
	</div>

  <div class="row container-fluid">
    <div class="col-6">
      <div class="card-header pastel_colour_red " style="text-align:center;">
          <h2>Favourite Bloggoes</h2>
        </div>
        <div class="card-body">
        <% if @favourite_blogs != nil && @favourite_blogs.count != 0%>
          <table class="table">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Author</th>
              <th scope="col">Visits</th>
            </tr>
            <% @favourite_blogs.each do |blog| %>
            <tr>
              <td><%= link_to blog.name, blog_path(blog) %></td>
              <td><%= blog.description %></td>
              <td><%= link_to blog.user.name, user_path(blog.user) %></td>
              <td><%= link_to blog.impressionist_count%></td>
            </tr>
            <% end %>
          </table>
          <% else %>
            <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    <div class="col-6">
      <div class="card">
        <div class="card-header pastel_colour_red " style="text-align:center;">
          <h2>Favourite Postoes</h2>
        </div>
        <div class="card-body">
        <% if @favourite_posts != nil && @favourite_posts.count != 0%>
          <%= render @favourite_posts %>
        <% else %>
          <h3> No bloggoes found! </h3>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>