config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations"
  }

  resources :users

  resources :search

  resources :tags, only: [:index, :show, :destroy]

  resources :blogs do
  	resources :posts do
  		resources :comments
      collection do
        get 'search'
      end
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'posts#downvote'
        get 'favourite', to: 'posts#favourite'
        get 'unfavourite', to:'posts#unfavourite'
      end
  	end
  end

  root 'home#index'
  get 'blogs/index'
  get 'search/index'
  
  get 'blogs/:id/visited_view' => "blogs#visited_view", :as => :visited_view
  get 'blogs/:id/recent_view' => "blogs#recent_view", :as => :recent_view
  get 'blogs/:id/reacted_view' => "blogs#reacted_view", :as => :reacted_view
  get 'blogs/:id/followed', to: 'blogs#follow', :as => :follow
  get 'blogs/:id/unfollowed', to: 'blogs#unfollow', :as => :unfollow
  get 'blogs/:id/change_suspended', to:'blogs#change_suspended', :as => :change_suspended
  get 'blogs/:id/favourite', to: 'blogs#favourite', :as => :favourite
  get 'blogs/:id/unfavourite', to:'blogs#unfavourite', :as => :unfavourite
  get 'users/upgrade/:id', to: 'users#upgrade', :as => :upgrade
  get 'users/:id/visited_view' => "users#visited_view", :as => :visited_user
  get 'users/:id/recent_view' => "users#recent_view", :as => :recent_user
  get 'blogs/:id/editors', to: 'blogs#editors', :as => :editors
  post 'blogs/:id/add_editors', to: 'blogs#add_editors', :as => :add_editor
  get 'blogs/:id/remove_editors/:user_id', to: 'blogs#remove_editors', :as => :remove_editor
  get 'admin_panel/index'
  get 'users/:id/change_status', to:'users#change_status', :as => :change_status
  get 'users/:id/all', to: 'users#all', :as => :see_all

  match '*path' => 'application#render_404', via: :all
end

app/models/post.rb
class Post < ApplicationRecord
	include Friendlyable
	
	acts_as_taggable_on :tags
	acts_as_votable
	acts_as_favoritable

	is_impressionable :counter_cache => true, :column_name => :impressions_count

	mount_uploader :file, FileUploader

	validates_integrity_of :file
	validates_processing_of :file

	has_many :comments, dependent: :destroy

	validates :title, presence: true, length: { minimum: 5, maximum: 100 }
	validates :subtitle, length: { maximum: 200 }
	validates :content, presence: true, length: { minimum: 1 }
	validates :user_id, presence: true

	validate :tag_list_count

	def tag_list_count
		errors[:tag_list] << "5 tags maximum" if tag_list.count > 5
		self.tag_list.each do |tag|
			errors[:tag_list] << "#{tag} must be shorter than 15 characters maximum" if tag.length > 15
			errors[:tag_list] << "#{tag} must be longer than 3 characters minimum" if tag.length < 3
		end
	end

	belongs_to :blog
	belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy, :upvote, :downvote, :favourite, :unfavourite ]
	before_action :check_editor, only: [ :new, :create ]
	before_action :check_user, only: [ :edit, :update ]
	before_action :check_destroy, only: [ :destroy ]
	impressionist actions: [ :show ], unique: [ :impressionable_type, :impressionable_id, :session_hash ]

	def index
		@blog = Blog.find(params[:blog_id])
		@posts = @blog.posts.paginate(page: params[:page], per_page: 5)
	end

	def show
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		@related_posts = Post.where.not(id: @post.id).tagged_with(@post.tag_list, any: true).order(:cached_weighted_average => :desc, :cached_votes_total => :desc, :impressions_count => :asc).first(3)
	end

	def new
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.build
	end

	def edit
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
	end

	def create
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.new(post_params)
		@post.user = current_user
		
		if post_params[:tag_list] == "" && post_params[:content] != ""
			api_key  = 'fHpDGKPcXGGMOpxtH9GFqaAEnbGhKyNGkePJXhFAQ54'
			response = RestClient.post "https://apis.paralleldots.com/v3/keywords", { api_key: api_key, text: @post.content }
			response = JSON.parse( response )
			if !response["keywords"][0].nil?
				keywords = response["keywords"].sort_by{ |word| word["confidence_score"].to_i }.reverse.select{ |word| word["keyword"].length <= 15 && word["keyword"].length >= 3}.first(5)
				keywords.each do |word|
					@post.tag_list = @post.tag_list + word["keyword"] + ","
				end
			end
		end

		if @post.save
			redirect_to blog_post_path(@blog, @post)
		else
			render 'new'
		end
	end

	def update
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])

		if params[:remove_file]
			@post.remove_file!
		end

		new_params = post_params

		if new_params[:tag_list] == "" && new_params[:content] != ""
			api_key  = 'fHpDGKPcXGGMOpxtH9GFqaAEnbGhKyNGkePJXhFAQ54'
			response = RestClient.post "https://apis.paralleldots.com/v3/keywords", { api_key: api_key, text: post_params[:content] }
			response = JSON.parse( response )
			if !response["keywords"][0].nil?
				keywords = response["keywords"].sort_by{ |word| word["confidence_score"].to_i }.reverse.select{ |word| word["keyword"].length <= 15 && word["keyword"].length >= 3}.first(5)
				keywords.each do |word|
					new_params[:tag_list] = new_params[:tag_list] + word["keyword"] + ","
				end
			end
		end

		if @post.update(new_params)
			redirect_to blog_post_path(@blog, @post)
		else
			render 'edit'
		end
	end

	def destroy
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		@post.destroy

		if current_user.admin?
			redirect_to admin_panel_index_path
		else
			redirect_to blog_path(@blog)
		end
	end

	def upvote
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		respond_to do |format|
			if current_user.voted_up_on? @post
				format.html { redirect_back fallback_location: root_path }
				format.json { head :no_content }
				format.js { render :layout => false }
				@post.cached_votes_total = @post.cached_votes_total - 1
				@post.save
				@post.unliked_by current_user
			else
				format.html { redirect_back fallback_location: root_path }
				format.json { head :no_content }
				format.js { render :layout => false }
				@post.cached_votes_total = @post.cached_votes_total + 1
				@post.save
				@post.upvote_by current_user
			end
		end
	end

	def downvote
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		respond_to do |format|
			if current_user.voted_down_on? @post
				format.html { redirect_back fallback_location: root_path }
				format.json { head :no_content }
				format.js { render :layout => false }
				@post.cached_votes_total = @post.cached_votes_total - 1
				@post.save
				@post.undisliked_by current_user
			else
				format.html { redirect_back fallback_location: root_path }
				format.json { head :no_content }
				format.js { render :layout => false }
				@post.cached_votes_total = @post.cached_votes_total + 1
				@post.save
				@post.downvote_by current_user
			end
		end
	end

	def favourite
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		current_user.favorite(@post)

		respond_to do |format|
			format.html { redirect_back fallback_location: root_path }
			format.json { head :no_content }
			format.js { render :layout => false }
		end
	end

	def unfavourite
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		current_user.remove_favorite(@post)

		respond_to do |format|
			format.html { redirect_back fallback_location: root_path }
			format.json { head :no_content }
			format.js { render :layout => false }
		end
	end


	private
	def post_params
		params.require(:post).permit(:title, :subtitle, :content, :tag_list, :file, :remove_file)
	end

	private
	def check_editor
		@blog = Blog.find(params[:blog_id])
		redirect_to blog_path(@blog) unless (@blog.user == current_user) || (!@blog.editors.nil? && @blog.editors.include?(current_user.id.to_s))
	end

	private
	def check_user
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		redirect_to blog_path(@blog) unless @post.user == current_user
	end

	private
	def check_destroy
		@blog = Blog.find(params[:blog_id])
		@post = @blog.posts.friendly.find(params[:id])
		redirect_to blog_path(@blog) unless (current_user.admin?) || (@blog.user == current_user) || (!@blog.editors.nil? && @blog.editors.include?(current_user.id.to_s)) || (!@post.nil? && @post.user == current_user)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def audio_path(source, options = {})
		path_to_asset(source, {type: :audio}.merge!(options))
	end
end

app/views/posts/_post.html.erb
<div class="card card-post-aux">
	<div class="card-body tg-wrap card-body-post-aux">
		<table class="table-post-aux">
			<tr>
				<td colspan="2" align="left"  valign="top">
					<% if post.user.avatar_image? %>
						<% if !post.user.avatar_image.thumb.nil? %>
							<%= image_tag(post.user.avatar_image.thumb.url, alt: post.user.username, class: 'image-link-aux') %>
						<% else %>
							<%= image_tag(post.user.avatar_image.url, alt: post.user.username, class: 'image-link-aux') %>
						<% end %>
					<% else %>
						<%= image_tag(asset_path('user-placeholder.jpeg'), alt: post.user.username, class: 'image-link-aux')  %>
					<% end %>
				</td>
				<td colspan="2" align="left" valign="center" class="post-title-aux">
					<h5 class="post-title"><%= link_to truncate(post.title, length: 20, omission: "..."), blog_post_path(post.blog, post), class: "post-link" %> <small class="text-muted text-small"> by </small>
						<% if post.user.username %>
							<%= link_to post.user.username, user_path(post.user), class: "post-link" %>
						<% else %>
							<%= link_to post.user.name, user_path(post.user), class: "post-link" %> 
						<% end %>
					</h5>
					<h6 class="text-muted post-subtitle"><%= truncate(post.subtitle, length: 25, omission: "...") %></h6>
				</td>
				<td align="right" valign="top" class="post-tags">
					<%= render post.tags %>
				</td>
			</tr>
			<tr>
				<td colspan="5">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="5" align="left" valign="center">
					<div class="fr-view post-content-aux">
						<%= 
							truncate(post.content.html_safe, 
							:length => 300, 
							:separator => '<a', 
	  						:omission => "... #{link_to 'Read more', blog_post_path(post.blog, post), class: 'post-link read-more'}".html_safe,
	  						:escape => false)
    					%>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="5">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="2" align="left">
					<aside class="vote-count bind-<%= post.id %>">
						<%= link_to like_blog_post_path(post.blog, post), :remote => true, method: :put, class: 'vpos post-link' do %>
							<i class="fas fa-thumbs-up like"></i>
							<span class="vcount-<%= post.id %>"><small><%= post.get_upvotes.size %></small></span>
						<% end %>
						<%= link_to dislike_blog_post_path(post.blog, post), :remote => true, method: :put, class: 'npos post-link' do %>
							<i class="fas fa-angry angry"></i>
							<span class="ncount-<%= post.id %>"><small><%= post.get_downvotes.size %></small></span>
						<% end %>
					</aside>
					<%= audio_tag asset_path('vote.mp3'), autoplay: false, controls: false, id: 'audio-vote' %>
				</td>
				<td colspan="2" align="left" class="post-comment-counter-aux">
					<%= link_to raw('<small class="text-muted"><i class="fas fa-comment"></i> Comments ').concat(post.comments.size.to_s).concat(raw('</small>')), blog_post_path(post.blog, post), class: "post-link post-comment-counter" %>
				</td>
				<td colspan="1" align="right">
					<% if user_signed_in? %>
						<% if current_user == post.user %>
							<div class="btn-group dropup">
								<a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-ellipsis-h"></i></a>
								<div class="dropdown-menu">
									<%= link_to raw('<i class="fas fa-trash-alt"></i> Delete'), [post.blog, post], method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
									<%= link_to raw('<i class="fas fa-edit"></i> Edit'), edit_blog_post_path(post.blog, post), class: "dropdown-item" %>
								</div>
							</div>
						<% elsif (post.blog.user == current_user) || (!post.blog.editors.nil? && post.blog.editors.include?(current_user.id.to_s)) || (current_user.admin?) %>
							<div class="btn-group dropup">
								<a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-ellipsis-h"></i></a>
								<div class="dropdown-menu">
									<%= link_to raw('<i class="fas fa-trash-alt"></i> Delete'), [post.blog, post], method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
								</div>
							</div>
						<% end %>
					<% end %>
				</td>
			</tr>
		</table>
	</div>
</div>

app/views/posts/downvote.js.erb
$('.npos').bind('ajax:success', function() {
	playSound();

	$('.ncount-<%= @post.id %>').html('<small><%= escape_javascript @post.get_downvotes.size.to_s %></small>');
	$('.vcount-<%= @post.id %>').html('<small><%= escape_javascript @post.get_upvotes.size.to_s %></small>');
});

app/views/posts/edit.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>Edit Post</h1>
		<%= render 'form' %>
		<%= link_to '<i class="fas fa-undo"></i> Back'.html_safe, blog_path(@post.blog), class: "btn btn-dark" %>
	</div>
</div>

app/views/posts/favourite.js.erb
$('.favourite-post').bind('ajax:success', function(){
	playSound();

	$(this).closest('.favourite-post').hide();
	$(this).closest('.favourite').html(' <%= link_to '<i class="far fa-heart post-favourite"></i>'.html_safe, unfavourite_blog_post_path(@blog, @post), method: :get, remote: true, class: 'unfavourite-post' %>');
});

app/views/posts/index.html.erb
<div class="container">
	<div class="jumbotron">
		<% if @posts %>
			<h3>Posts on <%= link_to @blog.name, blog_path(@blog), class: 'post-link' %></h3>
			<%= render @posts %>
			<%= will_paginate @posts, list_classes: %w(pagination justify-content-end pagination-sm pagination-margin), next_label: 'Next &raquo;', previous_label: '&laquo; Previous', aria_label: 'Posts Navigation' %>
		<% else %>
			<h3>There aren't posts for <%= link_to @blog.name, blog_path(@blog), class: 'post-link' %></h3>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>New Post</h1>
		<%= render 'form' %>
		<%= link_to '<i class="fas fa-undo"></i> Back'.html_safe, blog_path(@blog), class: "btn btn-dark" %>
	</div>
</div>

app/views/posts/show.html.erb
<script>
	$("head").append('<meta property="og:url"				content="<%= request.original_url %>" />');
	$("head").append('<meta property="og:type"				content="article" />');
	$("head").append('<meta property="og:title"				content="<%= @post.title %>" />');
	$("head").append('<meta property="og:description"		content="<%= @post.subtitle %>" />');
	$("head").append('<meta property="fb:app_id"			content="849655068560418" />');
	<% if @post.file.file.nil? %>
		$("head").append('<meta property="og:image"			content="<%= request.protocol + request.host_with_port + asset_path('favicon.png') %>" />');
	<% else %>
		<% if @post.file.file.extension.downcase == 'mp4' %>
			$("head").append('<meta property="og:video"			content="<%= request.protocol + request.host_with_port + @post.file.url %>" />');
		<% else %>
			$("head").append('<meta property="og:image"			content="<%= request.protocol + request.host_with_port + @post.file.url %>" />');
		<% end %>
	<% end %>
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v3.1&appId=849655068560418';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container">
	<div class="jumbotron">
		<table class="table-post-show">
			<tr>
				<td rowspan="2" class="post-td" valign="top">
					<div class="card post-card">
						<table class="post-table" align="center">
							<tr>
								<td colspan="4" align="left" valign="top" class="post-title-td">
									<% if @post.user.avatar_image? %>
										<% if !@post.user.avatar_image.thumb.nil? %>
											<%= image_tag(@post.user.avatar_image.thumb.url, alt: @post.user.name, class: "image-link") %>
										<% else %>
											<%= image_tag(@post.user.avatar_image.url, alt: @post.user.name, class: "image-link") %>
										<% end %>
									<% else %>
										<%= image_tag(asset_path('user-placeholder.jpeg'), alt: @post.user.name, class: "image-link") %>
									<% end %>
									<strong class="post-title"><%= @post.title %></strong>
									<small class="text-muted text-small"> posted on </small>
									<%= link_to @blog.name, blog_path(@blog), class: "post-link" %>
									<small class="text-muted text-small"> by </small>
									<% if @post.user.username %>
										<%= link_to @post.user.username, user_path(@post.user), class: "post-link" %>
									<% else %>
										<%= link_to @post.user.name, user_path(@post.user), class: "post-link" %> 
									<% end %>
									<small class="text-muted text-small"> &#8226; <%= time_ago_in_words(@post.created_at) %> ago</small>
								</td>
								<td align="right" valign="top">
									<% if user_signed_in? %>
										<% if current_user == @post.user %>
											<div class="dropdown">
												<a class="dropdown-toggle" id="dropdownMenuSettings" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-ellipsis-h"></i></a>
												<div class="dropdown-menu" aria-labelledby="dropdownMenuSettings">
													<%= link_to raw('<i class="fas fa-trash-alt"></i> Delete'), [@post.blog, @post], method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>  
													<%= link_to raw('<i class="fas fa-edit"></i> Edit'), edit_blog_post_path(@post.blog, @post), class: "dropdown-item" %>
												</div>
											</div>
										<% elsif (@blog.user == current_user) || (!@blog.editors.nil? && @blog.editors.include?(current_user.id.to_s)) || (current_user.admin?) %>
											<div class="dropdown">
												<a class="dropdown-toggle" id="dropdownMenuSettings" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-ellipsis-h"></i></a>
												<div class="dropdown-menu" aria-labelledby="dropdownMenuSettings">
													<%= link_to raw('<i class="fas fa-trash-alt"></i> Delete'), [@post.blog, @post], method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
												</div>
											</div>
										<% end %>
									<% end %>
								</td>
							</tr>
							<tr>
								<td colspan="5" align="center">
									<% if @post.file.file.nil? %>
										<br/>
									<% else %>
										<% if @post.file.file.extension.downcase == 'mp4' %>
											<%= video_tag(@post.file.url, controls: true, autobuffer: true, class: 'post-file')  %>
										<% else %>
											<%= image_tag(@post.file.url, alt: @post.file.identifier, class: 'post-file') %>
										<% end %>
									<% end %>
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left">
									<h6 class="card-subtitle post-subtitle mb-2 text-muted"><%= @post.subtitle %></h6>
								</td>
								<td colspan="2" align="right" class="post-tags">
									<%= render @post.tags %>
								</td>
							</tr>
							<tr>
								<td colspan="3" rowspan="2" align="left">
									<div class="fr-view post-content"><%= @post.content.html_safe %></div>
								</td>
								<td colspan="2" rowspan="2" align="right">
									&nbsp;
								</td>
							</tr>
							<tr>
							</tr>
							<tr valign="top" class="post-stats">
								<td align="left">
									<aside class="vote-count bind-<%= @post.id %>">
										<%= link_to like_blog_post_path(@blog, @post), :remote => true, method: :put, class: 'vpos post-link' do %>
											<i class="fas fa-thumbs-up like"></i>
											<span class="vcount-<%= @post.id %>"><small><%= @post.get_upvotes.size %></small></span>
										<% end %>
										<%= link_to dislike_blog_post_path(@blog, @post), :remote => true, method: :put, class: 'npos post-link' do %>
											<i class="fas fa-angry angry"></i>
											<span class="ncount-<%= @post.id %>"><small><%= @post.get_downvotes.size %></small></span>
										<% end %>
									</aside>
									<%= audio_tag asset_path('vote.mp3'), autoplay: false, controls: false, id: 'audio-vote' %>
								</td>
								<td align="left">
									<small class="text-muted"><i class="fas fa-comment"></i> Comments <%= @post.comments.size.to_s %></small>
								</td>
								<td colspan="2" align="right">
									<small class="text-muted"><i class="fas fa-eye"></i> <%= @post.impressions_count %> Views </small>
								</td>
								<td align="right" class="post-share-buttons" >
									<div class="g-plus" data-href="<% request.original_url %>" data-action="share" data-annotation="none"></div>
									<div class="fb-share-button" data-href="<%= request.original_url %>" data-layout="button" data-size="small" data-mobile-iframe="true"></div>
								</td>
							</tr>
							<tr>
								<td colspan="5" align="center" class="favourite">
									<% if user_signed_in? %>
										<% if current_user.favorited?(@post) %>
											<%= link_to unfavourite_blog_post_path(@blog, @post), method: :get, remote: true, class: 'unfavourite-post' do %>
												<i class="far fa-heart post-favourite"></i>
											<% end %>
										<% else %>
											<%= link_to favourite_blog_post_path(@blog, @post), method: :get, remote: true, class: 'favourite-post' do %>
												<i class="fas fa-heart post-favourite"></i>
											<% end %>
										<% end %>
									<% end %>	
								</td>
							</tr>
						</table>

						<% if user_signed_in? %>
							<div class="comments-form-new">
								<%= render partial: 'comments/form_new' %>
							</div>
						<% end %>

					  	<div class="comments-show">
					  		<% if @post.comments.size > 0 %>
					  			<hr>
								<%= nested_comments @post.comments.arrange(:order => :created_at) %>
							<% end %>
						</div>
					</div>
				</td>
				<td valign="top" class="blog-td">
					<div class="card blog-card" id="blog_card">
						<div class="tg-wrap">
							<table class="blog-table">
								<tr>
									<td colspan="2">
										<% if @blog.profile? %>
											<% if !@blog.profile.thumb.nil? %>
												<%= image_tag(@blog.profile.thumb.url, alt: @blog.name, class: "image-link") %>
											<% else %>
												<%= image_tag(@blog.profile.url, alt: @blog.name, class: "image-link") %>
											<% end %>
										<% else %>
											<%= image_tag(asset_path('user-placeholder.jpeg'), alt: @blog.name, class: "image-link") %>
										<% end %>
										<small class="card-title">
											<%= link_to @blog.name, blog_path(@blog), class: "post-link" %>
										</small>
									</td>
								</tr>
								<tr align="center" class="text-small">
									<td>Followers</td>
									<td>Posts</td>
								</tr>
								<tr align="center">
									<td>
										<small class="card-subtitle mb-2 text-muted text-small"><i class="fas fa-users"></i> <%= @blog.followers_count %></small>
									</td>
									<td>
										<small class="card-subtitle mb-2 text-muted text-small"><i class="fas fa-newspaper"></i> <%= @blog.posts.size %></small>
									</td>
								</tr>
								<tr>
								    <td colspan="2">
								    	<p class='blog-description'><i class="fas fa-angle-double-right"></i> <%= @blog.description %></p>
								    </td>
								</tr>
							</table>
						</div>
					</div>
					<div id="related_posts" class="related-posts">
						<% if @related_posts.size > 0 %>
							<small class="text-muted related-posts-title">Related Posts</small>
							<div class="related-posts-show"><%= render @related_posts %></div>
						<% end %>
					</div>
				</td>
			</tr>
		</table>
	</div>
</div>

app/views/posts/unfavourite.js.erb
$('.unfavourite-post').bind('ajax:success', function(){
	playSound();

	$(this).closest('.unfavourite-post').hide();
	$(this).closest('.favourite').html('<%= link_to '<i class="fas fa-heart post-favourite"></i>'.html_safe, favourite_blog_post_path(@blog, @post), method: :get, remote: true, class: 'favourite-post' %>');
});

app/views/posts/upvote.js.erb
$('.vpos').bind('ajax:success', function() {
	playSound();
	
	$('.vcount-<%= @post.id %>').html('<small><%= escape_javascript @post.get_upvotes.size.to_s %></small>');
	$('.ncount-<%= @post.id %>').html('<small><%= escape_javascript @post.get_downvotes.size.to_s %></small>');
});